### ISSUE TITLE
在执行npm install安装依赖报之前，项目对环境有什么特殊需求吗？

### ISSUE THREAD

**Issue by Iceyxm** [canfoo/vue2.0-taopiaopiao#12]
D:\NodeJs_workspace\taopiaopiao>npm install
npm WARN registry Unexpected warning for http://registry.npm.taobao.org/: Miscellaneous Warning ETIMEDOUT: request to http://registry.npm.taobao.org/babel-preset-es2015 failed, reason: connect ETIMEDOUT 114.55.80.225:80
npm WARN registry Using stale package data from http://registry.npm.taobao.org/ due to a request error during revalidation.
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

> node-zopfli@2.0.2 install D:\NodeJs_workspace\taopiaopiao\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\software\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\software\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\software\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\NodeJs_workspace\\taopiaopiao\\node_modules\\node
-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=D:\\NodeJs_workspace\\taopiaopiao\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd D:\NodeJs_workspace\taopiaopiao\node_modules\node-zopfli
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\software\nodejs\node.exe D:\software\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\NodeJs_workspace\taopiaopiao\node_mod
ules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\NodeJs_workspace\taopiaopiao\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\NodeJs_workspace\taopiaopiao\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "D:\\software\\nodejs\\node.exe" "D:\\NodeJs_workspace\\taopiaopiao\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\NodeJs_workspace\taopiaopiao\node_modules\node-zopfli
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'D:\software\nodejs\node.exe D:\software\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\NodeJs_workspace\taopiaopiao\node_modules\node-zopfli\lib\binding\no
de-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\NodeJs_workspace\taopiaopiao\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\NodeJs_workspace\taopiaopiao\node_modules\fsevents\node_modules'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 (node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 595 packages in 320.541s
无法安装依赖包，能帮忙看看是什么问题吗？感谢！

**Comment by canfoo** [comment]
建议你换台电脑试试，或者更新下你系统试试的。我这是在mac上开发的。

**Comment by jesse996** [comment]
同这个问题，解决了吗？

**Comment by canfoo** [comment]
@songzhixin1996 node v6.7.0+   npm v.3.10.3+ 试试样的版本
