### ISSUE TITLE
server 文件夹下面运行 npm run start 报错了 貌似说 sever  里的package有问题能帮我看看吗？

### ISSUE THREAD

**Issue by justinzpc** [canfoo/vue2.0-taopiaopiao#2]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.0.0
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart taopiaopiao-server@0.0.0
6 info start taopiaopiao-server@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info taopiaopiao-server@0.0.0 Failed to exec start script
9 verbose stack Error: taopiaopiao-server@0.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\lifecycle.js:222:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid taopiaopiao-server@0.0.0
11 verbose cwd D:\vue_pro\taobaopiao\vue2.0-taopiaopiao\server
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.4.5
15 error npm  v3.0.0
16 error code ELIFECYCLE
17 error taopiaopiao-server@0.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the taopiaopiao-server@0.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the taopiaopiao-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls taopiaopiao-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by canfoo** [comment]
已经先安装了package了吗。package是没问题的，试一下重装一个更高版本的node。

**Comment by justinzpc** [comment]
噢噢，谢谢我先去下一个最新的

**Comment by justinzpc** [comment]
可以了，谢谢！我打算再你项目基础上作一些修改 如果遇到问题再请教您

**Comment by canfoo** [comment]
客气了，OK～

**Comment by muxiaobai** [comment]
我下载后在运行server的时候，一直提示let SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
，请问一下是怎么回事？谢谢。

**Comment by canfoo** [comment]
运行：'npm run start:strict' 试一下

**Comment by muxiaobai** [comment]
server下面的app.js 中的一段，有问题，修改修改，参数重名
![default](https://cloud.githubusercontent.com/assets/13265901/23158978/05050676-f85c-11e6-912f-000f8c5c4fb1.PNG)

**Comment by canfoo** [comment]
这个没影响的，主要是处理webpack停止服务的请求，添加不添加都没影响。

**Comment by muxiaobai** [comment]
严格模式，不通过的。



![default](https://cloud.githubusercontent.com/assets/13265901/23159299/3df12180-f85d-11e6-8e67-735d2f1f642a.PNG)

**Comment by canfoo** [comment]
哦哦。刚才看错了，确实有错，谢谢告知哈
