### ISSUE TITLE
版本问题  请问下这个怎么解决

### ISSUE THREAD

**Issue by AlfieriChou** [canfoo/vue2.0-taopiaopiao#5]
ERROR in

Vue packages version mismatch:

- vue@2.2.1
- vue-template-compiler@2.2.2

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./src/main.js 61:8-35

**Comment by wzy4072** [comment]
我的也出现过类似的，
```
 error  in ./src/components/YgMenu.vue
Module build failed: Error:
Vue packages version mismatch:
- vue@2.4.1
- vue-template-compiler@2.3.4
This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to th
e latest.
```


应该是因为模块的版本有升级。解决办法就是升级对应模块
`npm install vue-template-compiler@latest -S`
@latest是模块最新版的意思，然后就ok了

**Comment by zhaocunyang** [comment]
不知道为什么官方这么升级 默认vue版本是2.4.3，而vue-template-compiler 最新版本是2.3.4就一直导致这个 问题 把vue版本改到2.3.*，然后从新npm install一下就解决这个恶心的版本问题了
