### ISSUE TITLE
编译后，无法正常访问。

### ISSUE THREAD

**Issue by muxiaobai** [canfoo/vue2.0-taopiaopiao#6]
## 1
在根目录下```npm run deploy ``` 后，无报错，
![default](https://cloud.githubusercontent.com/assets/13265901/24096997/f8fdff24-0d9e-11e7-9dc8-18bdb964d6d6.PNG)

然后进去server中```npm run start:strict``` ，无报错。
![123](https://cloud.githubusercontent.com/assets/13265901/24096982/e75697a4-0d9e-11e7-995e-8b99dd07b780.PNG)

但是访问的时候，就一直等待。
## 2
另外，启动server后，运行```npm run dev```的时候，可以成功。 

主要是因为8080端口其他的应用还要使用，所以就。。。

**Comment by canfoo** [comment]
1. 访问的时候，需要进入server里面启动后台服务的。
2. 什么意思？

**Comment by muxiaobai** [comment]
![222323232](https://cloud.githubusercontent.com/assets/13265901/24098512/a7ac559c-0da5-11e7-9b91-a670bbebbe0e.PNG)
就这段，不行，单启动server和运行```npm run dev``` It's OK.

**Comment by canfoo** [comment]
那这样是OK的，我看你截图都没有问题的。你是没有看到什么效果 ？
