### ISSUE TITLE
有关底部导航栏的问题

### ISSUE THREAD

**Issue by muxiaobai** [canfoo/vue2.0-taopiaopiao#8]
我看到底部使用footerNav.vue 这个组件，
上面的showNav的值是怎么改变的？
```
props: {
  	'showNav': {
  		type: Boolean,
  		default: true
  	}
  },
```
请教。

**Comment by canfoo** [comment]
在App.vue文件中，通过判断路径改变的

**Comment by muxiaobai** [comment]
问个问题，我的底部导航栏，第一次点击带连接的地方，可以跳转，然后在返回这个页面的时候，连接就无法点击是什么情况？

**Comment by canfoo** [comment]
具体是怎么操作的？我试了下，好像没有这个问题。
